### ISSUE TITLE
Cannot get status of IR sensor

### ISSUE THREAD

**Issue by jeroenterheerdt** [jeroenterheerdt/python-egardia#14]
hi @elpirato83, @jasper321, @ufulu, @Daehnie! I need your help. I am making good progress on sensor support for HA, but having some trouble seeing the status of IR sensors in my alarm control panel. Do you happen to know what the condition of an IR sensor is when a person is present? Please log into your alarm control panel and go to 'Panel condition', try to see if you can figure out what possible states are there for your sensors (IR, Door Contacts). Post them here, including your Egardia version. Thanks.

What I know (GATE-01):

- IR: no presence --> cond = ''
- DoorContact: closed --> cond = '', open --> cond = 'Open'

**Comment by Daehnie** [comment]
I‘ve the same Panel like you.

In the Installation Guide stands:
Please note! The motion detector incorporates a battery saving function of 1 minute. This means that the detector will only be active after it has not detected any motion for a period of 1 minute. When testing the motion detector ensure that the room has been empty for at least 1 minute before running the test.

I believe you can see only a status if your Panel is Armed.

**Comment by jeroenterheerdt** [comment]
Right, you might be right on the status only showing only when armed. For door contacts the status also shows when not armed, though.

**Comment by elpirato83** [comment]
I did a lot of tests trying to capture the status of the IR sensor during all states:
Armed, disarmed, home armed, walk test activated.
IR sensors trigger the system (in all states but Disarmed) but I wasn't able to notice a status change.
A search at the Internet learned me Egardia uses components from Climax. I think they use these IR sensors for the GATE-03:
http://www.climax.com.tw/ir16.php
Maybe these sensors only send a single RF signal when triggered?

Sensors showing a status change:
GATE-03:
"Door Contact"
closed --> "status": "Door Close"
open --> "status": "Door Open"

So for GATE-03 the "cond" data doesn't change at the Door Contacts

**Comment by jeroenterheerdt** [comment]
Thanks, this helps. I now looked at `cond`, did not know they used a different field in GATE-03,  figures.

**Comment by jeroenterheerdt** [comment]
@elpirato83 @Daehnie @ufulu please pull a new version and run `test_egardiadevice.py`. This should a False status when the door sensor is closed and a True status when the door sensor is open. The test selects a sensor randomly (so it might select a IR sensor). Still not sure how to deal with the IR sensor though. If we see no status changes at all, then there is no way to tell if the IR sensor has triggered or not.

**Comment by elpirato83** [comment]
I don't think the status of the IR sensor is very valuable at all because of the energy saving functionality.

Output:

Getting STATE
getstate output  ARM
------------
Getting SENSORS
getsensors output  {'RF:00e76910': {'cond_ok': '1', 'area': 1, 'zone': 3, 'su': 1, 'name': 'Schuifpui rechts', 'rssi': 'Strong, 9', 'battery': '', 'id': 'RF:00e76910', 'temp_bypass': '0', 'status': 'Door Close', 'battery_ok': '1', 'bypass': 'No', 'cond': '', 'type': 'Door Contact', 'tamper_ok': '1', 'tamper': ''}, 'RF:00f4fa10': {'cond_ok': '1', 'area': 1, 'zone': 6, 'su': 1, 'name': 'Voordeur', 'rssi': 'Strong, 9', 'battery': '', 'id': 'RF:00f4fa10', 'temp_bypass': '0', 'status': 'Door Close', 'battery_ok': '1', 'bypass': 'No', 'cond': '', 'type': 'Door Contact', 'tamper_ok': '1', 'tamper': ''}, 'RF:040be130': {'cond_ok': '1', 'area': 1, 'zone': 1, 'su': 1, 'name': 'Woonkamer voorzijde', 'rssi': 'Strong, 9', 'battery': '', 'id': 'RF:040be130', 'temp_bypass': '0', 'status': '', 'battery_ok': '1', 'bypass': 'No', 'cond': '', 'type': 'IR', 'tamper_ok': '1', 'tamper': ''}, 'RF:0409d730': {'cond_ok': '1', 'area': 1, 'zone': 2, 'su': 1, 'name': 'Woonkamer achterzijde', 'rssi': 'Strong, 9', 'battery': '', 'id': 'RF:0409d730', 'temp_bypass': '0', 'status': '', 'battery_ok': '1', 'bypass': 'No', 'cond': '', 'type': 'IR', 'tamper_ok': '1', 'tamper': ''}}
Selected random sensor:  RF:00f4fa10
getsensor( RF:00f4fa10 ) output  {'cond_ok': '1', 'area': 1, 'zone': 6, 'su': 1, 'name': 'Voordeur', 'rssi': 'Strong, 9', 'battery': '', 'id': 'RF:00f4fa10', 'temp_bypass': '0', 'status': 'Door Close', 'battery_ok': '1', 'bypass': 'No', 'cond': '', 'type': 'Door Contact', 'tamper_ok': '1', 'tamper': ''}
Traceback (most recent call last):
  File "test_egardiadevice.py", line 85, in <module>
    main()
  File "test_egardiadevice.py", line 48, in main
    print("getsensorstate(",randomsensorID,") output ",eg.getsensorstate(randomsensorID))
  File "/home/arjan/python-egardia/src/pythonegardia/egardiadevice.py", line 174, in getsensorstate
    if sensor['status'].upper() == "DOOR OPEN" | len(sensor['status'])>0:
TypeError: unsupported operand type(s) for |: 'str' and 'int'

**Comment by jeroenterheerdt** [comment]
@elpirato83 good catch, new version is ready. Please re-test. WRT your comment on IR sensors, you are right. So for now I would be happy if the component supported the door sensors as I do not own smoke sensors of egardia. Anyway, thanks to all your help (and others!) we getting closer!

**Comment by elpirato83** [comment]
@jeroenterheerdt It was/is my pleasure to provide you the info! Thank you for your effort getting this to work!
This might be the last full output for now (because it looks like it completely works 😉):

> Getting STATE
> getstate output  ARM
> ------------
> Getting SENSORS
> getsensors output  {'RF:00f4fa10': {'zone': 6, 'bypass': 'No', 'id': 'RF:00f4fa10', 'area': 1, 'name': 'Voordeur', 'tamper': '', 'temp_bypass': '0', 'su': 1, 'rssi': 'Strong, 9', 'battery_ok': '1', 'battery': '', 'cond_ok': '1', 'tamper_ok': '1', 'cond': '', 'status': 'Door Close', 'type': 'Door Contact'}, 'RF:0409d730': {'zone': 2, 'bypass': 'No', 'id': 'RF:0409d730', 'area': 1, 'name': 'Woonkamer achterzijde', 'tamper': '', 'temp_bypass': '0', 'su': 1, 'rssi': 'Strong, 9', 'battery_ok': '1', 'battery': '', 'cond_ok': '1', 'tamper_ok': '1', 'cond': '', 'status': '', 'type': 'IR'}, 'RF:00e76910': {'zone': 3, 'bypass': 'No', 'id': 'RF:00e76910', 'area': 1, 'name': 'Schuifpui rechts', 'tamper': '', 'temp_bypass': '0', 'su': 1, 'rssi': 'Strong, 9', 'battery_ok': '1', 'battery': '', 'cond_ok': '1', 'tamper_ok': '1', 'cond': '', 'status': 'Door Close', 'type': 'Door Contact'}, 'RF:040be130': {'zone': 1, 'bypass': 'No', 'id': 'RF:040be130', 'area': 1, 'name': 'Woonkamer voorzijde', 'tamper': '', 'temp_bypass': '0', 'su': 1, 'rssi': 'Strong, 9', 'battery_ok': '1', 'battery': '', 'cond_ok': '1', 'tamper_ok': '1', 'cond': '', 'status': '', 'type': 'IR'}}
> Selected random sensor:  RF:00e76910
> getsensor( RF:00e76910 ) output  {'zone': 3, 'bypass': 'No', 'id': 'RF:00e76910', 'area': 1, 'name': 'Schuifpui rechts', 'tamper': '', 'temp_bypass': '0', 'su': 1, 'rssi': 'Strong, 9', 'battery_ok': '1', 'battery': '', 'cond_ok': '1', 'tamper_ok': '1', 'cond': '', 'status': 'Door Close', 'type': 'Door Contact'}
> getsensorstate( RF:00e76910 ) output  True
> ------------
> IMPORTANT: continuing passed this point will arm and disarm your alarm!
> Press y to ARM your alarm y
> Sent arm command to alarm, waiting 10 seconds...
> getstate output (should be ARM)  ARM
> Press y to DISARM your alarm y
> Sent disarm command to alarm, waiting 10 seconds...
> getstate output (should be DISARM)  DISARM
> Press y to HOME ARM your alarm y
> Sent home arm command to alarm, waiting 10 seconds...
> getstate output (should be HOME)  HOME
> Press y to DISARM your alarm y
> Sent disarm command to alarm, waiting 10 seconds...
> getstate output (should be DISARM)  DISARM
> Tests completed
> 
>

**Comment by jeroenterheerdt** [comment]
We are not done yet, but for the component it seems fine now. I have a working version in Hass as well, but need to clean up the code. When done Let's figure out how you can test that on your Egardia before publishing it in the next version of Hass.

**Comment by elpirato83** [comment]
Sounds like a plan :wink:
