### ISSUE TITLE
States update speed

### ISSUE THREAD

**Issue by misteriks** [jeroenterheerdt/python-egardia#24]
I have a WV-1716

I would like to use the alarm status and door contacts in HomeAssistant automations, but problem is that is takes a long time before the states get updated in HA. Sometime up to 30 seconds.

Is there a way to get instant updates of these states?

**Comment by jeroenterheerdt** [comment]
the updates should be immediate. have you ran the tests and see if the status gets surfaced immediately there?

**Comment by misteriks** [comment]
I used egardiaserver.py to capture all codes and when doing that I also noticed a delay.

E.g. open door > 20-30 seconds later the code showed up in my shell

**Comment by jeroenterheerdt** [comment]
then you will have to look into the config of your alarm if you can spot a delay there. normally this would be immediate.

**Comment by misteriks** [comment]
If I check http://192.168.x.y/action/sensorListGet and open a door then the status changes in about 2 seconds. 
The sensor update in Hassio takes 20-30 seconds.

**Comment by jeroenterheerdt** [comment]
there is no reason in this repos code that would case the delay that I can see, so unfortunately it seems like the alarm itself is not calling the server quickly enough. Do you have the IP where your egardiaserver.py runs as the primary IP in your alarms config?

**Comment by misteriks** [comment]
Do other models have a primary and secondary report server?

My WV-1716 only has one
![22 43 06 10-03-{$YYYY}](https://user-images.githubusercontent.com/324504/76362050-98b01000-6320-11ea-8a16-63a785c6d848.png)


I'll see if I can do some testing with Wireshark

**Comment by jeroenterheerdt** [comment]
yes, others have a primary and secondary.

**Comment by misteriks** [comment]
So, how does the communication actually work? 

Does HassIO pull the sensor info from the Egardia device or does it listen to the info the Egardia device sends to the report server that is running on HassIO?

Cause I updated the report server IP to be my PC so I could listen with Wireshark, but I don't see any traffic coming in and my HassIO still reports the status changes of my door sensor

**Comment by jeroenterheerdt** [comment]
The HA component talks to the egardiaserver that is running. HA will remember the status though.

**Comment by alexandruionica** [comment]
So I think there may be a misunderstanding here as there are two different things which is the status of the binary sensors for door contacts and the events the gateway is sending to home assistant whenever something happens.
I have triple checked and the status of the binary sensors for the door contacts does take up to 30 seconds to be updated in home assistant. As far as I can see:
- home assistant fetches the data for the binary sensors from the gateway, via a http connection to port 80 of the gateway (I have a GATE-01 model). I validated this with tcp dump. Hence the reason for the delay
- the integration code doesn't seem to have a mention of the update interval ( https://developers.home-assistant.io/docs/integration_fetching_data/ ) so this would mean the default of 30 seconds is used to poll the data from the gateway.

Now the reason I care about this because I want to have some automation done based on the state of these door contacts, irrespective of if the alarm is armed or not.
Ideally we would have some kind of push events but I have yet to try to get the "Push Server Setting" of the gateway to point at some http capture server on my machine and see if anything of use is shipped there (and anyway it seems to have some kind of periodic update interval setting).

Otherwise, the best other solution I can think of is if it would be possible to configure the interval of fetching the data for the binary sensors, away from the default. Given the closed nature of the gateway, I don't know if a more frequent http poll of what I suspect is GET /action/sensorListGet would lead to performance issues for the gateway itself (I am not aware of a way of running `top` or anything remotely similar on it/from it).

Regards.

**Comment by misteriks** [comment]
Hi Alex,

Must be a coincidence, but yesterday I removed all Egardia components from my home and I build my own alarm system in Home Assistant. With xiaomi door and motion sensors and a Centralite 3400-D keypad.

This delivers the same functionality as the (old) Egardia system I had and it saves me on the monthly €10 I paid to only receive sms and call notifications + I have more flexibility and adding extra sensors is cheaper than the Egardia sensors. 

Maybe something you can consider as well.

**Comment by jeroenterheerdt** [comment]
I did the exact same thing a couple of years ago - definitely recommend that route

**Comment by alexandruionica** [comment]
Well I've setup for myself Amazon Pinpoint Voice and Amazon Pinpoint SMS and hooked it up via a lambda to home assistant so I can get the same notifications I used to get from Egardia/WoonVeilig but for a fraction of the price (it costs $1 USD to rent a US phone number from AWS,and otherwise you pay cents per phone call or SMS). I like to have standalone systems which are integrated into HomeAssistant but can otherwise function mostly independent, hence I'm ok with keeping the Egardia alarm up and running with the only dependency on Homeassistant being for notifications. 
This being said, I can do some extra non alarm related things with door contact sensors but only as long as I actually get the event soon (or at all) and in the current setup I can open the door, enter, close the door within seconds and Home assistant would most likely never know because it polls the data one in 30 seconds, so between two poll intervals it won't see any change (door remains closed).
