### ISSUE TITLE
Trigger the alarm (from Home Assistant)

### ISSUE THREAD

**Issue by SilvanLaroo** [jeroenterheerdt/python-egardia#32]
Hi @jeroenterheerdt,

Thanks for this great implementation, I'm using it with my Home Assistant setup. I followed every step to make the Alarm work in Home Assistant and everything works as expected but I have on additional question. Is it possible to trigger the alarm from Home Assistant? When I run the trigger service in HA for this alarm, nothing changes. I would like to make this work, so I can trigger the alarm based on other HA events.

Regards,
Silvan

**Comment by jeroenterheerdt** [comment]
Thanks for checking in! I don't own this alarm any more so am unable to expand on this. Last time I checked there was no way to trigger the alarm, but I have not looked at it (or owned one of these) in years. So unfortunately unless someone else knows you're on your own

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: SilvanLaroo ***@***.***>
Sent: Sunday, October 3, 2021 5:23:43 AM
To: jeroenterheerdt/python-egardia ***@***.***>
Cc: Jeroen ter Heerdt ***@***.***>; Mention ***@***.***>
Subject: [jeroenterheerdt/python-egardia] Trigger the alarm (from Home Assistant) (#32)


Hi @jeroenterheerdt<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjeroenterheerdt&data=04%7C01%7C%7C1b98e460ddfa465c799408d98668a408%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637688606247047026%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=y6HwlxkraSCEkrQmTuFbpBvo0nY1mNZk7dDF6OgGEfg%3D&reserved=0>,

Thanks for this great implementation, I'm using it with my Home Assistant setup. I followed every step to make the Alarm work in Home Assistant and everything works as expected but I have on additional question. Is it possible to trigger the alarm from Home Assistant? When I run the trigger service in HA for this alarm, nothing changes. I would like to make this work, so I can trigger the alarm based on other HA events.

Regards,
Silvan

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjeroenterheerdt%2Fpython-egardia%2Fissues%2F32&data=04%7C01%7C%7C1b98e460ddfa465c799408d98668a408%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637688606247057023%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QjVIVGSHA%2FeZyRoYB5Y%2FDlX1ydQDKyEQmhtggvpHwRQ%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB6PIPQGOKRACKM4ZZDNBB3UFBDM7ANCNFSM5FHRWGBA&data=04%7C01%7C%7C1b98e460ddfa465c799408d98668a408%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637688606247057023%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3KCvs%2FHWgJQyXry9%2FEd9dHEa0%2BrAx9dphZC2nD3mF3c%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C1b98e460ddfa465c799408d98668a408%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637688606247067014%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5fDCOeSjE%2FRmkvIj11mnW10pSJZwr2FxPclQsZv9Mfs%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C1b98e460ddfa465c799408d98668a408%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637688606247067014%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lXUhKFG2qAYCSjHKNOjLsi%2F4jlRruLJjoZ9cL6JF7zI%3D&reserved=0>.

**Comment by SilvanLaroo** [comment]
Alright, thanks for your reply!
